image upload route and handler implementation
RohanDas-max/eKYC pull request #3
Opened 2022-03-10 06:28 UTC by RohanDas-max

- Image Upload route implementation

**Note**
- Unit tests yet to be implemented
- for generating uuid using faker for now

2022-03-23 06:02 UTC, iamargus95 requested changes

2022-03-23 06:02 UTC, iamargus95 commented on pkg/services/signupService.go
> +	if err := utils.ValidateEmail(r.Email); err != nil {
Is there a need for validate Email utils now?

2022-03-23 06:11 UTC, RohanDas-max commented on pkg/services/signupService.go
> +	if err := utils.ValidateEmail(r.Email); err != nil {
the validate email util is checking for the domains also...do binding validation checks for domain also??

2022-03-28 07:20 UTC, iamargus95 approved these changes

2022-03-28 11:55 UTC, merged