Facematch
RohanDas-max/eKYC pull request #4
Opened 2022-03-28 13:48 UTC by RohanDas-max

1. router,handler,services,reqbody setup for face-match api
2. query for uuid and tests done

2022-03-30 07:14 UTC, iamargus95 requested changes

2022-03-30 07:14 UTC, iamargus95 commented on pkg/handler/faceMatch.go
> +	score, err := services.FaceMatchService(c, &r)
new line

2022-03-30 07:14 UTC, iamargus95 commented on pkg/handler/faceMatch.go
> +	c.JSON(http.StatusOK, gin.H{
new line

2022-03-30 07:14 UTC, iamargus95 commented on pkg/handler/faceMatch_test.go
> +func TestFaceMatch(t *testing.T) {
use t.Setenv in all tests.

2022-03-30 07:14 UTC, iamargus95 commented on pkg/handler/faceMatch_test.go
> +		}, {
rectify indentation here.
and also add tests to fulfill empty cases and same uuids in both fields.

2022-03-30 07:14 UTC, iamargus95 commented on pkg/handler/faceMatch_test.go
> +			c.Request, _ = http.NewRequest(http.MethodPost, "api/v1/signup", bytes.NewBuffer(requestData))
why is it hitting api/v1/signup?

2022-03-30 07:14 UTC, iamargus95 commented on pkg/handler/uploadImage.go
> +	uuid, err := services.UploadService(c, r.Type, file, *fileHeader)
new line

2022-03-30 07:14 UTC, iamargus95 commented on pkg/models/fileMetadata.go
>  type FileMetaData struct {
why no gorm.model?

2022-03-30 07:14 UTC, iamargus95 commented on pkg/routers/router.go
>  	r.NoRoute(func(ctx *gin.Context) {
Move to a separate file under controllers.

2022-03-30 07:14 UTC, iamargus95 commented on pkg/services/faceMatchService.go
> +		if cachedScore == "" {
new line

2022-03-30 07:14 UTC, iamargus95 commented on pkg/services/faceMatchService.go
> +	if err != nil && res == "" {
why check for res == ""?

2022-03-30 07:14 UTC, iamargus95 commented on pkg/services/faceMatchService.go
> +func isUUIDExists(r resources.FaceMatchReqBody, clientId int) bool {
move to helper functions.

2022-03-30 07:14 UTC, iamargus95 commented on pkg/services/faceMatchService.go
> +func cachedScore(c *gin.Context, key string, value int) (string, error) {
move to helper func or utils.

2022-03-30 07:14 UTC, iamargus95 commented on pkg/services/faceMatchService_test.go
> +		os.Getenv("DB_HOST"), os.Getenv("DB_USER"), os.Getenv("DB_PASSWORD"), os.Getenv("DB_DBNAME"), os.Getenv("DB_PORT"), os.Getenv("DB_SSLMODE"), os.Getenv("DB_TIMEZONE"))
t.Setenv.

2022-03-30 07:14 UTC, iamargus95 commented on pkg/services/faceMatchService_test.go
> +	tests := []struct {
Improve tests by adding more cases. Have a case for same uuid's

2022-03-30 07:14 UTC, iamargus95 commented on pkg/services/faceMatchService_test.go
> +		})
No checking for gotRes?

2022-03-30 07:14 UTC, iamargus95 commented on pkg/services/faceMatchService_test.go
> +		os.Getenv("DB_HOST"), os.Getenv("DB_USER"), os.Getenv("DB_PASSWORD"), "ekyc", os.Getenv("DB_PORT"), os.Getenv("DB_SSLMODE"), os.Getenv("DB_TIMEZONE"))
t.Setenv

2022-03-30 07:14 UTC, iamargus95 commented on pkg/services/imageUploadService.go
> +	database.InsertIntoFileMetadata(typ, filepath.Ext(info.Key), uuid, int(info.Size/1024), id)
db transaction error/

2022-03-31 06:05 UTC, iamargus95 approved these changes

2022-03-31 06:14 UTC, merged

2022-03-31 09:58 UTC, kalpeshdeo commented
Please address the comments above